/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    '✓ On': '✓ 开',
    '✗ Off': '✗ 关',
    'Achievements': '成就',
    'Additive': '添加剂',
    'Arcades': '街机',
    'Auto': '自动',
    'Cloud Saving': '云存储',
    'Cloud': '云端',
    'Confirm': '确认',
    'Cost': '成本',
    'Cost: $': '成本: $',
    'Currently Each': '当前每个',
    'Exchange': '转换',
    'Favors': '帮助',
    'Forever': '永远',
    'Forever AutoBuy': '永远自动购买',
    'Tickets': '门票',
    'total)': '总计)',
    'total': '总计',
    'tap!': '点击!',
    'Max': '最大',
    'Lease': '租赁',
    'Mana': '法力',
    'Mixed': '混合',
    'More Coming Soon!': '更多内容及将推出！',
    'Offline Progress': '离线进度',
    'On': '开',
    'Net Income: $': '净利润:$',
    'No Cloud Save Detected': '未检测到云存档',
    'Reset': '重置',
    'Reset To Get': '重置以获得',
    'Retain All': '保留所有',
    'Retain': '保留',
    'Score': '分数',
    'Savings: $': '节省:$',
    'Share Alerts': '股票提醒',
    'Share Multi': '股票加成',
    'Share/Arcade': '股票/街机',
    'Shop': '商店',
    'Basic Upgrade': '几本升级',
    'Better': '更好',
    'Cancel': '取消',
    'Cash Out': '提现',
    'Donations': '捐款',
    'Earn': '获取',
    'First Upgrades': '首次升级',
    'Info': '信息',
    'Keep': '保留',
    'More Shares': '更多股票',
    'Machine Upgrades': '机器升级',
    'Alerts': '提醒',
    'Also Makes Zones Permanent': '也使区域成为永久性的',
    'Also retains those investor upgrades': '也保留那些投资者升级',
    'Any and all donations are greatly appreciated.': '非常感谢所有的捐赠。',
    'Arcade Multi': '街机加成',
    'Autobuy': '自动购买',
    'AutoBuy': '自动购买',
    'AutoBuy Shares': '自动购买股票',
    'Automatic': '自动化',
    'Automatic Paddles': '自动拨片',
    'You are ready for your first machine upgrades': '您已经准备好进行第一次机器升级',
    'Wizard Upgrades (Scrollable': '巫师升级 (可滚动',
    'x Points': 'x 点数',
    'You can get multiple payouts per card.': '每张卡你可以得到多次支付。',
    'You notice a man watching you constantly as you gain wealth and investors, when confronted he tells you that ever since he was a young boy, he\'s played the silver ball. From Soho down to Brighton he must have played them all. But he hasn\'t seen anything like you in any amusement hall, and would like to offer you transcended power if you would sacrifice your belongings and supporters.': '你注意到一个男人一直在看着你，看着你获得财富和投资者，当他面对你的时候，他告诉你，从他还是个小男孩的时候，他就玩过银色的球。从索霍到布赖顿，他肯定都玩过。但他从未在任何娱乐场所见过像你这样的人，如果你愿意牺牲自己的财产和支持者，他会给你超越的权力。',
    'Once Per Round Each, Both Multiply Eachother': '每轮一次，两者相乘',
    'Notes': '说明',
    'Ok': '好的',
    'Numbers': '数字',
    'On Prestige': '声望',
    'Point Tripler': '点数三倍',
    'Points': '点数',
    'Game AutoSaves Locally, Cloud Saves are limited to Kongregate': '游戏本地自动保存，云保存仅限于Kongregate',
    'Game Discord': '游戏 Discord',
    'Gives Auto Paddles ability to operate separately and faster': '给予自动拨片能力，操作分开和更快',
    'Upgrade': '升级',
    'Upgrades': '升级',
    'Upgrades allow you to increase the number of points you get from hits.': '升级允许你增加你从击中中获得的点数。',
    'Upgrade Retainer': '升级护圈',
    'Use your investors\' connections to get bleeding edge technology': '利用投资者的人脉获取前沿技术',
    'Use your points to buy in-game machine upgrades to increase your points income': '使用你的点数购买游戏中的机器升级，以增加你的点数收入',
    'Use your transcended power to ease your next life': '用你超越的力量来放松你的来生',
    'Version: v': '版本: v',
    'Wait...I Can Only Get One??': '等等…我只能得到一个??',
    'Welcome Back!': '欢迎回来!',
    'Which is just one guy developing during quarantine': '隔离期间只有一个人在开发',
    'Wizard Alerts': '巫师提醒',
    'AutoExchange': '自动转换',
    'Assistant': '助手',
    'AutoGet Favors': '自动获取帮助',
    'AutoPaddles': '自动踏板',
    'AutoPaddles and': '自动踏板和',
    'AutoReset For Shares': '自动重置股票',
    'Welcome': '欢迎',
    'Welcome to my quarantine project,': '欢迎来到我在隔离期开发的作品，',
    'Pincremental': '弹珠增量',
    'I hope you enjoy this Pinball-Based Incremental.': '我希望你能享受这个基于弹珠的增量游戏。',
    'Shoot for a high score or just let it idle,': '为了更高的分数而射击或者只是让它自己弹弹弹',
    'Buys Side Blockers': '购买侧挡块',
    'Buys Tripler': '购买三倍频器',
    'Call in Favors': '请求帮助',
    'Call In Favors': '请求帮助',
    'Cash Out To Get': '提现以获得',
    'Competitors start coming to you offering powerful favors in exchange for shares of your current company': '竞争对手开始向你提供强有力的帮助，以换取你目前公司的股份',
    'Conversion Requires 300+ Shares': '转换需要300 +股票',
    '¢ More': '¢ 更多',
    'Available': '可用',
    'Automation': '自动化',
    'Bonus': '奖励',
    'Become': '成为',
    'Basic Point Multiplier': '基础点数加成',
    'Buys Auto Paddles': '购买自动拨片',
    'Pinball Mana': '弹珠法力',
    'Heard you like retainers, so here\'s a retainer': '听说您喜欢固定器，所以这里有一个固定器',
    'high score': '高分',
    'High Score': '高分',
    'Hire': '雇佣',
    'The Current Score Exponent One': '当前得分指数1',
    'The Current Score Multi One': '当前得分倍数1',
    'The First One': '第一个',
    'The Bumper One': '保险杠1',
    'The Basic Automators One': '基本自动化器1',
    'The Incomplete One': '不完整1',
    'This Menu is May Be Rebalanced, Mana Refunds Will Occur if So': '此菜单可能会被重新平衡，如果被重新平衡，法力会被退回',
    'This game was developed by Makopaz Games.': '这个游戏是由Makopaz游戏公司开发的。',
    'Triple': '三倍',
    'Triple Points': '三倍点数',
    'Triple Tickets': '三倍门票',
    'Tripler': '三倍器',
    'Triples your total points from hits': '使你的总点数增加三倍',
    'Unspent': '未用的',
    'The Pinball icon in the bottom-left will light up when upgrades are available.': '当升级可用时，左下角的弹球图标将点亮。',
    'Automatically Hits the Balls at an Interval When Near Paddles': '当靠近拍子时，自动在一个间隔击中球',
    'Welcome!': '欢迎!',
    'Arrow keys can also be used to control flippers (Click into game first!': '箭头键也可以用来控制挡板(先点击进入游戏!',
    'Welcome to my quarantine project, Pincremental!': '欢迎来到我的隔离项目，弹珠增量!',
    'I hope you enjoy this Pinball-Based Incremental. Shoot for a high score or just let it idle, either way I hope it will help you spend some of this time at home.': '我希望你喜欢这个基于弹球的增量。争取高分或让它放置起来，无论哪种方式，我希望它能帮助你花一些时间在家里。',
    'Hold down upgrade button to buy multiple': '按下升级按钮购买倍数',
    'If stuck, press Shift+R to': '如果卡住，按Shift+R去',
    'If you enjoyed this game, please do let me know!': '如果你喜欢这个游戏，请告诉我!',
    'In an effort to get more gamers involved in the parent company. The arcade is running a promotion exchanging equity for tickets.': '为了让更多的玩家参与到母公司中来。街机正在进行一项促销活动，以换取门票。',
    'Hated That Button Anyway': '讨厌那个按钮',
    'Get Multiplier from': '获得倍数从',
    'Get this one': '得到这一个',
    'Get Extra Lives to Reach Higher Scores': '获得额外的生命，以达到更高的分数',
    'For Shares': '对股票',
    'From Resets': '通过重置',
    'Always looking to improve it, so please let me know in the forums or comments any feedback you have positive, constructive, or negative :': '一直在寻求改进，所以请让我知道在论坛或评论任何反馈你有积极的，建设性的，或消极的:',
    'After all this work for others, you decide to start your own side business and use your new contacts in corporate investing to secure investors for this new venture': '在为别人做了这些工作之后，你决定开始自己的副业，并利用你在公司投资方面的新人脉来为这个新项目争取投资者',
    'After Others': '在别人之后',
    'Buys Doubler': '购买双倍器',
    'Buys Extra Lives': '购买额外的生命',
    'Buys HS Multi': '购买HS加成',
    'Buys Multiplier Zones': '购买倍数区',
    'Best to convert for 4-5 Favors at first, getting more is easier later on': '一开始最好是转化4-5个帮助，以后得到更多就容易多了',
    'Multiplies your point income by (X% of your Current Hits +': '乘以你的点数收入(X%你当前命中+',
    'Multiplies your point income by (X% of your High Score +': '乘以你的点数收入(X%你的高分+',
    'Multis': '倍数',
    'Payouts are determined by how many of the same icon you get.': '支付是由多少相同的图标，你得到。',
    'Permanent': '永久',
    'Pinball Mechanic Upgrades': '弹珠机械升级',
    'Pinball Mechanic Upgrades Available In Ticket Menu': '弹珠机制升级在们票菜单中可用',
    'Puts the executive assistant on retainer so they never reset': '把行政助理放在固定位置，这样他们就不会重置',
    'Raises Your Current Score Multiplier to the X Power': '将当前的分数乘数提高到X次方',
    'Press Shift+R if your ball gets stuck': '如果你的球卡住了，按Shift+R',
    'Popup': '弹出',
    'Multi': '倍数',
    'reset ball': '重置弹珠',
    'Retainers': '固定器',
    'Retains AutoReset & AutoLease': '保留自动重置和自动租赁',
    'Retains Favor AutoExchange': '保留优先自动交换',
    'Retains those investor upgrades': '保留那些投资者升级',
    'Gravity simulates rolling': '重力模拟滚动',
    'Increase': '增加',
    'on a slanted table': '在倾斜的桌子上',
    '- Gravity simulates rolling': '-重力模拟滚动',
    '- Made with JS/HTML please excuse physics imperfections': '-使用JS / HTML制作，请原谅物理缺陷',
    'Earned': '获得的',
    'Earned Points/': '获得的点数 /',
    'Earned Tickets/': '获得的门票 /',
    'Enjoy!': '享受吧!',
    'Exponent': '指数',
    'Exponent by .': '指数。',
    'Extra Lives': '额外生命',
    'Extra Life': '额外生命',
    'Upgrade AutoBuyers': '升级自动购买者',
    'Will Now Only Reset On Mana Prestige': '现在只重置法力声望吗',
    'Save to': '保存到',
    'Save to the cloud to play on multiple computers and protect your save against browser cache clearing': '保存到云，以在多台计算机上运行，并保护您的保存免受浏览器缓存清理',
    'Saving/Loading': '保存/加载',
    'Score Exp': '分数经验',
    'Shares': '股票',
    'Score Power': '得分能力',
    'The High Score Multi One': '最高分倍数1',
    'The Retainment One': '保留1',
    'The Ticket One': '门票1',
    'Doubler': '双倍器',
    'Doubles Favors Recieved on Exchange': '转换时收到双份帮助',
    'Doubles your total points from hits': '从点击中获得总点数翻倍',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

    //原样
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "Auto ": "自动 ",
    "AutoGet ": "自动获取 ",
    "Current ": "当前 ",
    "Ticket ": "门票 ",
    "Total ": "总计 ",
    "Double ": "双倍 ",
    "High Score ": "高分 ",
    "Retainment ": "保留 ",
    "Investor ": "投资者 ",
    "Sacrifice ": "牺牲 ",
    "Cash out your game for tickets and start again": "把你的比赛门票兑换成现金，然后重新开始",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    " ": "",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "\n": "",
    "Achievements": "成就",
    "Favors": "帮助",
    "Investors": "投资者",
    "Lifetime Investors": "终生投资者",
    "Lifetime Pinball Mana": "终生弹珠法力",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?[A-Za-z%]{0,2}(\s.C)?\s*$/, //12.34K,23.4 °C
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /^\s*$/, //纯空格
    /^\d+(\.\d+)?[A-Za-z]{0,2}.?\(?([+\-]?(\d+(\.\d+)?[A-Za-z]{0,2})?)?$/, //12.34M (+34.34K
    /^(\d+(\.\d+)?[A-Za-z]{0,2}\/s)?.?\(?([+\-]?\d+(\.\d+)?[A-Za-z]{0,2})?\/s\stot$/, //2.74M/s (112.4K/s tot
    /^\d+(\.\d+)?(e[+\-]?\d+)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?$/, //2.177e+6 (+4.01+4
    /^(\d+(\.\d+)?(e[+\-]?\d+)?\/s)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?\/s\stot$/, //2.177e+6/s (+4.01+4/s tot
];
var cnExcludePostfix = [
    /:?\s*x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^You were offline for (.+) Hours. While offline you earned (.+) Points! Thanks for coming back!$/, '你离线了 $1 小时。离线时你获得 $2 点数!感谢你回来!'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);